"""Generate ``manuscript/references.bib`` from the indexed corpus.

The corpus (``bibliography/mandatory_sources.csv``) carries authors, short
titles and identifiers for every source. This script emits a BibTeX entry for
each, and records in the ``metadata_verified`` column which entries have been
independently checked against the source rather than merely indexed.

The distinction is load-bearing and is preserved in the output: every entry
carries a ``note`` stating its verification status, so a reader of the ``.bib``
can tell at a glance which references were confirmed and which were taken from
the supplied index. Fabricating journal/volume/page data for unverified entries
would be worse than omitting it, so unverified entries carry only what the
corpus actually contains.
"""

from __future__ import annotations

import argparse
import csv
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]

# Entries independently verified against the source (search or known-standard
# reference), with the extra metadata that verification established.
VERIFIED: dict[str, dict] = {
    "A01": {"journal": "Annals of Physics", "volume": "172", "pages": "304",
            "year": "1986"},
    "A02": {"journal": "Living Reviews in Relativity", "volume": "11",
            "pages": "6", "year": "2008"},
    "A06": {"journal": "Progress of Theoretical Physics", "volume": "120",
            "pages": "561", "year": "2008"},
    "A15": {"year": "2023"},
    "A16": {"journal": "Physics Letters B", "year": "2025"},
    "A17": {"journal": "Physical Review D", "year": "2026"},
    "B19": {"year": "2021"},
    "B22": {"year": "2024"},
    "B30": {"year": "2025"},
    "C36": {"journal": "Physical Review X", "volume": "11", "pages": "031003",
            "year": "2021"},
    "D51": {"journal": "Proceedings of the Royal Society A", "volume": "402",
            "pages": "285", "year": "1985"},
    "E63": {"journal": "Reviews of Modern Physics", "volume": "93",
            "pages": "015005", "year": "2021"},
    "E65": {"journal": "Physical Review Letters", "volume": "127",
            "pages": "186601", "year": "2021"},
    "E66": {"year": "2022"},
    "E67": {"journal": "Journal of Computational Physics", "year": "2020"},
    "E71": {"publisher": "Springer", "year": "1995"},
    "E72": {"publisher": "Princeton University Press", "year": "2005"},
    "E73": {"publisher": "SIAM", "year": "2009"},
    "E74": {"publisher": "Princeton University Press", "year": "2011"},
}

# Used for the benchmark but absent from the supplied corpus.
EXTRA = [
    {"key": "Matyjasek2021", "authors": "Matyjasek, J.",
     "title": "Quasinormal modes of Schwarzschild-Tangherlini black holes",
     "identifier": "arXiv:2107.04815", "year": "2021", "verified": True,
     "note": "Source of the 12-digit ST5D benchmark reproduced here."},
    {"key": "KravanjaVanBarel2000",
     "authors": "Kravanja, P. and Van Barel, M.",
     "title": "Computing the Zeros of Analytic Functions",
     "identifier": "", "year": "2000", "publisher": "Springer",
     "verified": True,
     "note": "Contour-moment root finding used by the zero-counting routine."},
]


def bibkey(row: dict) -> str:
    first = re.split(r"[;,]", row["authors"])[0].strip()
    first = re.sub(r"[^A-Za-z]", "", first) or "Anon"
    ident = row.get("identifier", "")
    # New-style arXiv:YYMM.NNNNN
    m = re.search(r"\b(\d{2})(\d{2})\.\d{4,5}", ident)
    if m:
        yy = int(m.group(1))
        yr = f"20{yy:02d}"
    else:
        # Old-style arXiv:archive/YYMMNNN -- the year is the FIRST two digits
        # of the seven-digit number, and 9x means 19xx.  Parsing these with a
        # generic four-digit match produced keys like "Nollert2032".
        m = re.search(r"/(\d{2})(\d{2})(\d{3})\b", ident)
        if m:
            yy = int(m.group(1))
            yr = f"{'19' if yy >= 90 else '20'}{yy:02d}"
        else:
            m2 = re.search(r"\b(19|20)\d{2}\b", ident)
            yr = m2.group(0) if m2 else ""
    return f"{first}{yr}{row['id']}"


def fmt_authors(a: str) -> str:
    parts = [p.strip() for p in a.split(";") if p.strip()]
    if not parts:
        return "{Unknown}"
    return " and ".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="bibliography/mandatory_sources.csv")
    ap.add_argument("--out", default="manuscript/references.bib")
    ap.add_argument("--update-csv", action="store_true",
                    help="write the verification status back to the corpus")
    args = ap.parse_args()

    rows = list(csv.DictReader(open(ROOT / args.csv)))
    lines = [
        "% Generated by scripts/build_bibliography.py from",
        "% bibliography/mandatory_sources.csv. Do not edit by hand.",
        "%",
        "% Every entry states whether its metadata was INDEPENDENTLY VERIFIED or",
        "% merely INDEXED from the supplied corpus. Journal/volume/page fields",
        "% appear only for verified entries: inventing them for the rest would",
        "% be worse than omitting them.",
        "",
    ]
    n_ver = 0
    for r in rows:
        key = bibkey(r)
        r["_key"] = key
        ident = r.get("identifier", "").strip()
        extra = VERIFIED.get(r["id"], {})
        verified = r["id"] in VERIFIED
        n_ver += bool(verified)

        is_book = ident == "book" or "publisher" in extra
        etype = "book" if is_book else "article"
        fields = [f"  author  = {{{fmt_authors(r['authors'])}}}",
                  f"  title   = {{{r['short_title']}}}"]
        for k in ("journal", "volume", "pages", "publisher", "year"):
            if k in extra:
                fields.append(f"  {k:<7} = {{{extra[k]}}}")
        if ident.startswith("arXiv:"):
            fields.append(f"  eprint  = {{{ident.split(':', 1)[1]}}}")
            fields.append("  archivePrefix = {arXiv}")
        elif ident and ident != "book":
            fields.append(f"  note    = {{{ident}}}")
        status = ("metadata independently verified" if verified
                  else "INDEXED from the supplied corpus; metadata not "
                       "independently verified")
        fields.append(f"  note    = {{{status}.}}"
                      if not (ident and not ident.startswith("arXiv:")
                              and ident != "book")
                      else f"  annote  = {{{status}.}}")
        lines.append(f"@{etype}{{{key},")
        lines.append(",\n".join(fields))
        lines.append("}\n")

    for e in EXTRA:
        n_ver += 1
        fields = [f"  author  = {{{e['authors']}}}",
                  f"  title   = {{{e['title']}}}"]
        for k in ("publisher", "year"):
            if k in e:
                fields.append(f"  {k:<7} = {{{e[k]}}}")
        if e["identifier"].startswith("arXiv:"):
            fields.append(f"  eprint  = {{{e['identifier'].split(':', 1)[1]}}}")
            fields.append("  archivePrefix = {arXiv}")
        fields.append(f"  note    = {{{e['note']} Metadata independently "
                      f"verified.}}")
        lines.append(f"@{'book' if 'publisher' in e else 'article'}{{{e['key']},")
        lines.append(",\n".join(fields))
        lines.append("}\n")

    out = ROOT / args.out
    out.write_text("\n".join(lines))
    print(f"wrote {out}: {len(rows) + len(EXTRA)} entries, "
          f"{n_ver} independently verified")

    if args.update_csv:
        p = ROOT / args.csv
        with open(p, "w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=[c for c in rows[0]
                                               if not c.startswith("_")])
            w.writeheader()
            for r in rows:
                r["metadata_verified"] = "1" if r["id"] in VERIFIED else "0"
                w.writerow({k: v for k, v in r.items()
                            if not k.startswith("_")})
        print(f"updated {p}")

    # emit the citation-key map so the manuscript can reference by corpus id
    keymap = ROOT / "manuscript" / "citekeys.txt"
    keymap.write_text("\n".join(f"{r['id']}\t{r['_key']}\t{r['short_title']}"
                                for r in rows) + "\n")
    print(f"wrote {keymap}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
