"""Compact, committable manifest of the branch atlas.

The atlas itself is ~24 MB of JSON and is regenerated by
``scripts/build_branch_atlas.py``, so it is deliberately **not** committed.
What is committed is this manifest: per-sector and per-branch summaries, the
domain, the failure census, and a content hash of each shard, which is enough to
verify a regenerated atlas matches the one the results were computed from.
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import pathlib
import subprocess


def commit_hash() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    except Exception:  # noqa: BLE001
        return "unknown"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--atlas-dir", default="data/full_branch_atlas")
    ap.add_argument("--out", default="results/full_branch_atlas.json")
    args = ap.parse_args()

    d = pathlib.Path(args.atlas_dir)
    sectors, total, fails = [], 0, collections.Counter()
    for f in sorted(d.glob("sector_*.json")):
        raw = f.read_bytes()
        s = json.loads(raw)
        total += s["n_points"]
        for x in s["failures"]:
            fails[x["reason"]] += 1
        per_branch = collections.Counter(p["branch"] for p in s["points"])
        pts = s["points"]
        sectors.append({
            "sector": s["sector"],
            "n_points": s["n_points"],
            "n_failures": s["n_failures"],
            "n_branches": len(per_branch),
            "points_per_branch": dict(sorted(per_branch.items())),
            "max_residual": max(p["residual"] for p in pts) if pts else None,
            "max_predictor_miss": max(p["predictor_miss"] for p in pts) if pts else None,
            "r_minus_range": [min(p["z_minus"] for p in pts) ** 0.5,
                              max(p["z_minus"] for p in pts) ** 0.5] if pts else None,
            "extremality_min": min(p["extremality"] for p in pts) if pts else None,
            "sha256": hashlib.sha256(raw).hexdigest(),
            "provenance": s.get("provenance", {}),
        })

    out = {
        "status": "complete",
        "provenance": {"commit": commit_hash()},
        "note": "The atlas data itself is not committed (~24 MB). Regenerate with "
                "scripts/build_branch_atlas.py and compare sha256 per shard.",
        "n_atlas_points": total,
        "n_sectors": len(sectors),
        "failure_census": dict(fails),
        "sectors": sectors,
    }
    pathlib.Path(args.out).write_text(json.dumps(out, indent=1) + "\n")
    print(f"wrote {args.out}: {total} points across {len(sectors)} sectors")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
